### ISSUE TITLE
Application launch problem

### ISSUE THREAD

**Issue by smoriarti** [PeerJ/PeerJDocxFormatter#8]
Was not able to launch the Formatter. What are the requirements?
I got "unable to access jarfile PereJDocxFormatter.jar" from the command prompt.

**Comment by michaelstoner** [comment]
It seems you have a typo, it's `PeerJDocxFormatter.jar` and not `PereJDocxFormatter.jar`

https://github.com/PeerJ/PeerJDocxFormatter#peerjdocxformatter

**Comment by smoriarti** [comment]
Nope, made a typo here, not in a command prompt! Still got this 
"unable to access jarfile PeerJDocxFormatter.jar"

**Comment by michaelstoner** [comment]
It's a message from Java itself saying that it cannot find the the file named  "PeerJDocxFormatter.jar".  
Hence if the name on the command prompt was incorrect you would have that error.  If the name is correct then maybe the path is not, but your issue is related to the "unable to access jarfile" rather than this project.
